# Generated by Django 2.2.5 on 2020-05-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200517_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='SanskritamMember',
        ),
    ]
