# Generated by Django 2.2.5 on 2020-05-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_sanskritammember_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SanskritamMember',
            new_name='CourseMember',
        ),
    ]
